name: Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history + submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: Fetch top-level tags
        run: git fetch --force --tags

      - name: Fetch submodule tags
        run: git submodule foreach --recursive "git fetch --force --tags"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Semantic Release (tag & GitHub Release)
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
